# 1 - Getting Started with TensorFlow

In [1]:
import tensorflow as tf
import numpy as np

/Library/Anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.6 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.7
  return f(*args, **kwds)


## Declaring Tensors

### 1.1 Fixed tensors:



In [2]:
row_dim = 4
col_dim = 5
sess = tf.Session()

In [3]:
#Create a zero filled tensor. Use the following:
zero_tsr = tf.zeros([row_dim, col_dim])
print(zero_tsr)
sess.run(zero_tsr)

Tensor("zeros:0", shape=(4, 5), dtype=float32)


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)

In [4]:
# Create a one filled tensor. Use the following: 
ones_tsr = tf.ones([row_dim, col_dim])
print(ones_tsr)
sess.run(ones_tsr)

Tensor("ones:0", shape=(4, 5), dtype=float32)


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)

In [5]:
#Create a constant filled tensor. Use the following: 
filled_tsr = tf.fill([row_dim, col_dim], 42)
print(filled_tsr)
sess.run(filled_tsr)

Tensor("Fill:0", shape=(4, 5), dtype=int32)


array([[42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42]], dtype=int32)

In [6]:
#Create a tensor out of an existing constant. Use the following:
constant_tsr = tf.constant([1,2,3])
print(constant_tsr)
sess.run(constant_tsr)

Tensor("Const:0", shape=(3,), dtype=int32)


array([1, 2, 3], dtype=int32)

### 1.2 Tensors of similar shape

In [7]:
#We can also initialize variables based on the shape of other tensors, as follows:
zeros_similar = tf.zeros_like(constant_tsr)
ones_similar = tf.ones_like(constant_tsr)
print(zeros_similar,'\n', ones_similar)
print('zeros_similar: ', sess.run(zeros_similar))
print('ones_similar: ', sess.run(ones_similar))



Tensor("zeros_like:0", shape=(3,), dtype=int32) 
 Tensor("ones_like:0", shape=(3,), dtype=int32)
zeros_similar:  [0 0 0]
ones_similar:  [1 1 1]


### 1.3 Sequence tensors:

In [8]:
# TensorFlow allows us to specify tensors that contain defined intervals. The following functions behave very 
# similarly to the range() outputs and numpy's linspace() outputs. See the following function:
linear_tsr = tf.linspace(start=0.0, stop=1, num=3)
print(linear_tsr)
sess.run(linear_tsr)

Tensor("LinSpace:0", shape=(3,), dtype=float32)


array([0. , 0.5, 1. ], dtype=float32)

In [9]:
# The resulting tensor is the sequence [0.0, 0.5, 1.0]. 
# Note that this function includes the specified stop value. See the following function:
# The result is the sequence [6, 9, 12]. Note that this function does not include the limit value.
integer_seq_tsr = tf.range(start=6, limit=15, delta=3)
print(integer_seq_tsr)
sess.run(integer_seq_tsr)

Tensor("range:0", shape=(3,), dtype=int32)


array([ 6,  9, 12], dtype=int32)

### 1.4 Random tensors:

In [10]:
# Note that this random uniform distribution draws from the interval 
# that includes the minval but not the maxval (minval <= x < maxval).
randunif_tsr = tf.random_uniform([row_dim, col_dim], minval=0, maxval=1)
print(randunif_tsr)
sess.run(randunif_tsr)

Tensor("random_uniform:0", shape=(4, 5), dtype=float32)


array([[0.7912855 , 0.4553269 , 0.9440459 , 0.18774247, 0.6759523 ],
       [0.76959527, 0.60909295, 0.42014956, 0.51050353, 0.19272888],
       [0.12932575, 0.71849   , 0.02474761, 0.6868391 , 0.59169483],
       [0.4085058 , 0.9336953 , 0.4273454 , 0.8807064 , 0.7339244 ]],
      dtype=float32)

In [11]:
# To get a tensor with random draws from a normal distribution, as follows:
randnorm_tsr = tf.random_normal([row_dim, col_dim], mean=0.0, stddev=1.0)
print(randnorm_tsr)
sess.run(randnorm_tsr)

Tensor("random_normal:0", shape=(4, 5), dtype=float32)


array([[-0.27968043,  1.8213042 ,  0.7313014 ,  1.156326  , -0.69455653],
       [-0.51916957, -1.174872  , -0.88730067, -0.22928411, -0.8486738 ],
       [ 0.5022169 , -0.88140327,  0.710257  , -0.03452583, -0.722225  ],
       [-0.15739939, -0.3070296 ,  0.58209103, -0.5447573 ,  0.7729796 ]],
      dtype=float32)

In [12]:
# There are also times when we wish to generate normal random values that are assured within certain bounds.
# The truncated_normal() function always picks normal values within two standard deviations of the specified mean.
# See the following:
runcnorm_tsr = tf.truncated_normal([row_dim, col_dim], mean=0.0, stddev=1.0)
print(runcnorm_tsr)
sess.run(runcnorm_tsr)

Tensor("truncated_normal:0", shape=(4, 5), dtype=float32)


array([[ 0.22587982, -0.7041513 , -1.6064415 , -1.121558  ,  0.73343486],
       [-0.54530483,  1.0190886 ,  1.3497546 , -0.2436367 ,  0.5042937 ],
       [ 0.834888  , -0.10719744, -1.6145267 , -1.2179449 ,  0.21531558],
       [ 1.1177862 ,  1.1505157 ,  0.4790224 , -0.63684785,  1.9048425 ]],
      dtype=float32)

- We might also be interested in randomizing entries of arrays. To accomplish this, there are two functions that help us: ```random_shuffle()``` and ``random_crop()``. See the following:

In [13]:
# shuffled_output = tf.random_shuffle(runcnorm_tsr)
# cropped_output = tf.random_crop(runcnorm_tsr, 2)

# print('shuffled_output: ', shuffled_output, sess.run(shuffled_output))
# print('cropped_output: ', cropped_output,sess.run(cropped_output))


In [14]:
# Later on in this book, we will be interested in randomly cropping an image of size (height, width, 3) where there are three color spectrums. To fix a dimension in the cropped_output, you must give it the maximum size in that dimension:
#cropped_image = tf.random_crop(my_image, [height/2, width/2, 3])

## Using Placeholders and Variables


Placeholders and variables are key tools for using computational graphs in TensorFlow. We must understand the difference and when to best use them to our advantage.
### Getting ready
One of the most important distinctions to make with the data is whether it is a placeholder or a variable. Variables are the parameters of the algorithm and TensorFlow keeps track of how to change these to optimize the algorithm. Placeholders are objects that allow you to feed in data of a specific type and shape and depend on the results of the computational graph, such as the expected outcome of a computation.

In [15]:
my_var = tf.Variable(tf.zeros([2,3]))
sess = tf.Session()
initialize_op = tf.global_variables_initializer ()
sess.run(initialize_op)
sess.run(my_var)

array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [16]:
sess = tf.Session()
x = tf.placeholder(tf.float32, shape=[2,2])
y = tf.identity(x)
x_vals = np.random.rand(2,2)
sess.run(y, feed_dict={x: x_vals})
# Note that sess.run(x, feed_dict={x: x_vals}) will result in a self-referencing error.

array([[0.92516834, 0.7077631 ],
       [0.72848994, 0.38107234]], dtype=float32)

During the run of the computational graph, we have to tell TensorFlow when to initialize the variables we have created. TensorFlow must be informed about when it can initialize the variables. While each variable has an initializer method, the most common way to do this is to use the helper function, which is `global_variables_initializer()`.
This function creates an operation in the graph that initializes all the variables we have created, as follows:



In [17]:
initializer_op = tf.global_variables_initializer()
sess.run(initializer_op)

But if we want to initialize a variable based on the results of initializing another variable, we have to initialize variables in the order we want, as follows:

In [18]:
sess = tf.Session()
first_var = tf.Variable(tf.zeros([2,3]))
sess.run(first_var.initializer)
second_var = tf.Variable(tf.zeros_like(first_var))
# Depends on first_var
sess.run(second_var.initializer)

## Working with Matrices

In [19]:
sess = tf.Session()

1. Creating matrices: We can create two-dimensional matrices from numpy arrays or nested lists, as we described in the earlier section on tensors. We can also use the tensor creation functions and specify a two-dimensional shape for functions such as `zeros()`, `ones()`, `truncated_normal()`, and so on. TensorFlow also allows us to create a diagonal matrix from a one-dimensional array or list with the function `diag()`, as follows:

In [20]:
identity_matrix = tf.diag([1.0, 1.0, 1.0])
A = tf.truncated_normal([2,3])
B = tf.fill([2,3], 5.0)
C = tf.random_uniform([3,2])
D = tf.convert_to_tensor(np.array([[1., 2., 3.],[-3., -7., -1.],[0., 5., -2.]]))
print('identity_matrix: \n', sess.run(identity_matrix))
print('A: \n', sess.run(A))
print('B: \n', sess.run(B))
print('C: \n', sess.run(C))
print('D: \n', sess.run(D))

identity_matrix: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
A: 
 [[ 0.41711855 -0.7454542  -0.11365662]
 [-0.16381666  0.33388212  0.18860054]]
B: 
 [[5. 5. 5.]
 [5. 5. 5.]]
C: 
 [[0.85718024 0.1441617 ]
 [0.01697803 0.9305912 ]
 [0.356102   0.19079506]]
D: 
 [[ 1.  2.  3.]
 [-3. -7. -1.]
 [ 0.  5. -2.]]


In [21]:
# Addition and subtraction uses the following function: 
print(sess.run(A+B))

[[4.9937425 5.021853  3.2444577]
 [4.5673265 3.3217802 6.2834606]]


In [22]:
print(sess.run(B-B))

[[0. 0. 0.]
 [0. 0. 0.]]


In [23]:
# Also, the function matmul() has arguments that specify whether or not to transpose
# the arguments before multiplication or whether each matrix is sparse.

print(sess.run(tf.matmul(B, identity_matrix)))

[[5. 5. 5.]
 [5. 5. 5.]]


In [24]:
# Transpose the arguments as follows:
print(sess.run(tf.transpose(C)))

[[0.91107595 0.45836318 0.54793143]
 [0.24193418 0.35453534 0.25038493]]


In [25]:
# For the determinant, use the following:
print(sess.run(tf.matrix_determinant(D)))

-37.99999999999999


In [26]:
# Inverse
print(sess.run(tf.matrix_inverse(D)))

[[-0.5        -0.5        -0.5       ]
 [ 0.15789474  0.05263158  0.21052632]
 [ 0.39473684  0.13157895  0.02631579]]


In [27]:
# For the Cholesky decomposition, use the following:
print(sess.run(tf.cholesky(identity_matrix)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
# For Eigenvalues and eigenvectors, use the following code:
print(sess.run(tf.self_adjoint_eig(D)))

(array([-10.65907521,  -0.22750691,   2.88658212]), array([[ 0.21749542,  0.63250104, -0.74339638],
       [ 0.84526515,  0.2587998 ,  0.46749277],
       [-0.4880805 ,  0.73004459,  0.47834331]]))


In [29]:
print(sess.run(tf.div(3,4)))

0


In [30]:
print(sess.run(tf.truediv(3,4)))

0.75


In [31]:
# If we have floats and want an integer division
print(sess.run(tf.floordiv(3.0,4.0)))

0.0


In [32]:
print(sess.run(tf.mod(22.0, 5.0)))

2.0


In [33]:
# The cross-product between two tensors is achieved
print(sess.run(tf.cross([1., 0., 0.], [0., 1., 0.])))

[0. 0. 1.]


In [34]:
# Tangent function (tan(pi/4)=1)
print(sess.run(tf.div(tf.sin(3.1416/4.), tf.cos(3.1416/4.))))

1.0000036


In [35]:
def custom_polynomial(value):
    return(tf.subtract(3 * tf.square(value), value) + 10)
print(sess.run(custom_polynomial(11)))


362


### Implementing Activation Functions

In [36]:
print(sess.run(tf.nn.relu([-3., 3., 10.])))

[ 0.  3. 10.]


In [37]:
#The implementation that TensorFlow has is called the ReLU6 function. This is defined as min(max(0,x),6). 
# This is a version of the hard- sigmoid function and is computationally faster, and does not suffer from 
# vanishing (infinitesimally near zero) or exploding values. 
print(sess.run(tf.nn.relu6([-3., 3., 10.])))

[0. 3. 6.]


In [38]:
# The sigmoid function is the most common continuous and smooth activation function. 
# It is also called a logistic function and has the form 1/(1+exp(-x)). 
print(sess.run(tf.nn.sigmoid([-1., 0., 1.])))

[0.26894143 0.5        0.7310586 ]


In [39]:
# The hyper tangent function is very similar to the sigmoid except that instead of having a range 
# between 0 and 1, it has a range between -1 and 1. 
print(sess.run(tf.nn.tanh([-1., 0., 1.])))

[-0.7615942  0.         0.7615942]


In [40]:
# The form of this function is x/(abs(x) + 1). 
print(sess.run(tf.nn.softsign([-1., 0., -1.])))

[-0.5  0.  -0.5]


In [41]:
# Another function, the softplus, is a smooth version of the ReLU function. The form of this 
# function is log(exp(x) + 1).
print(sess.run(tf.nn.softplus([-1., 0., -1.])))

[0.31326166 0.6931472  0.31326166]


In [42]:
# The Exponential Linear Unit (ELU) is very similar to the softplus function except that the bottom 
# asymptote is -1 instead of 0. The form is (exp(x)+1) if x < 0 else x.
print(sess.run(tf.nn.elu([-1., 0., -1.])))

[-0.63212055  0.         -0.63212055]


# Working with Data Sources

**Iris data:** This dataset is arguably the most classic dataset used in machine learning and maybe all of statistics. It is a dataset that measures sepal length, sepal width, petal length, and petal width of three different types of iris flowers: Iris setosa, Iris virginica, and Iris versicolor. There are 150 measurements overall, 50 measurements of each species. To load the dataset in Python, we use Scikit Learn's dataset function, as follows:

In [43]:
from sklearn import datasets

iris = datasets.load_iris()
len(iris.data)

150

In [44]:
len(iris.target)

150

In [45]:
iris.data[0] # Sepal length, Sepal width, Petal length, Petal width

array([5.1, 3.5, 1.4, 0.2])

**Birth weight data:** The University of Massachusetts at Amherst has compiled many statistical datasets that are of interest (1). One such dataset is a measure of child birth weight and other demographic and medical measurements of the mother and family history. There are 189 observations of 11 variables. Here is how to access the data in Python:

In [46]:
import requests

birthdata_url = 'https://github.com/nfmcclure/tensorflow_cookbook/raw/master/01_Introduction/07_Working_with_Data_Sources/birthweight_data/birthweight.dat'
birth_file = requests.get(birthdata_url)
birth_data = birth_file.text.split('\r\n')
birth_header = birth_data[0].split('\t')
birth_data = [[float(x) for x in y.split('\t') if len(x)>=1] for y in birth_data[1:] if len(y)>=1]
print(len(birth_data))
print(len(birth_data[0]))

189
9


**Boston Housing data:** Carnegie Mellon University maintains a library of datasets in their Statlib Library. This data is easily accessible via The University of California at Irvine's Machine-Learning Repository (2). There are 506 observations of house worth along with various demographic data and housing attributes (14 variables). Here is how to access the data in Python:

In [47]:
# Housing Price Data
from keras.datasets import boston_housing
(x_train, y_train), (x_test, y_test) = boston_housing.load_data()
housing_header = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
print(x_train.shape[0])
print(x_train.shape[1])

Using TensorFlow backend.


57344/57026 [==============================] - 0s 6us/step
404
13


**MNIST handwriting data:** MNIST (Mixed National Institute of Standards and Technology) is a subset of the larger NIST handwriting database. The MNIST handwriting dataset is hosted on Yann LeCun's website (https://yann.lecun. com/exdb/mnist/). It is a database of 70,000 images of single digit numbers (0-9) with about 60,000 annotated for a training set and 10,000 for a test set. This dataset is used so often in image recognition that TensorFlow provides built-in functions to access this data. In machine learning, it is also important to provide validation data to prevent overfitting (target leakage). Because of this TensorFlow, sets aside 5,000 of the train set into a validation set. Here is how to access the data in Python:


In [48]:
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)
print(len(mnist.train.images))
print(len(mnist.test.images))
print(len(mnist.validation.images))
print(mnist.train.labels[1,:]) # The first label is a 3'''

Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
Instructions for updating:
Please write your own downloading logic.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST_data/train-images-idx3-ubyte.gz
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Instructions for updating:
Please use tf.one_hot on tensors.
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
55000
10000
5000
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


**Spam-ham text data:** UCI's machine -learning data set library (2) also holds a spam- ham text message dataset. We can access this .zip file and get the spam-ham text data as follows:


In [49]:
import requests
import io
from zipfile import ZipFile
zip_url = 'http://archive.ics.uci.edu/ml/machine-learning-databases/00228/smsspamcollection.zip'
r = requests.get(zip_url)
z = ZipFile(io.BytesIO(r.content))
file = z.read('SMSSpamCollection')
text_data = file.decode()
text_data = text_data.encode('ascii',errors='ignore')
text_data = text_data.decode().split('\n')
text_data = [x.split('\t') for x in text_data if len(x)>=1]
[text_data_target, text_data_train] = [list(x) for x in zip(*text_data)]
print(len(text_data_train))
print(set(text_data_target))
print(text_data_train[1])

5574
{'spam', 'ham'}
Ok lar... Joking wif u oni...


**Movie review data:** Bo Pang from Cornell has released a movie review dataset that classifies reviews as good or bad (3). You can find the data on the website, http:// www.cs.cornell.edu/people/pabo/movie-review-data/. To download, extract, and transform this data, we run the following code:
       

In [50]:
import requests
import io
import tarfile
movie_data_url = 'http://www.cs.cornell.edu/people/pabo/movie-review-data/rt-polaritydata.tar.gz'
r = requests.get(movie_data_url)
# Stream data into temp object
stream_data = io.BytesIO(r.content)
tmp = io.BytesIO()
while True:
   s = stream_data.read(16384)
   if not s:
       break
   tmp.write(s)
stream_data.close()
tmp.seek(0)
# Extract tar file
tar_file = tarfile.open(fileobj=tmp, mode="r:gz")
pos = tar_file.extractfile('rt-polaritydata/rt-polarity.pos')
neg = tar_file.extractfile('rt-polaritydata/rt-polarity.neg')
# Save pos/neg reviews (Also deal with encoding)
pos_data = []
for line in pos:
   pos_data.append(line.decode('ISO-8859-1').encode('ascii',errors='ignore').decode())
neg_data = []
for line in neg:
   neg_data.append(line.decode('ISO-8859-1').encode('ascii',errors='ignore').decode())
tar_file.close()
print(len(pos_data))
print(len(neg_data))
# Print out first negative review
print(neg_data[0])

5331
5331
simplistic , silly and tedious . 



**CIFAR-10 image data:** The Canadian Institute For Advanced Research has released an image set that contains 80 million labeled colored images (each image is scaled to 32x32 pixels). There are 10 different target classes (airplane, automobile, bird, and so on). The CIFAR-10 is a subset that has 60,000 images. There are 50,000 images in the training set, and 10,000 in the test set. Since we will be using this dataset in multiple ways, and because it is one of our larger datasets, we will not run a script each time we need it. To get this dataset, please navigate to http://www. cs.toronto.edu/~kriz/cifar.html, and download the CIFAR-10 dataset. We will address how to use this dataset in the appropriate chapters.


**The works of Shakespeare text data:** Project Gutenberg (5) is a project that releases electronic versions of free books. They have compiled all of the works of Shakespeare together. The following code shows you how to access this text file through Python:

In [51]:
import requests 
shakespeare_url = 'http://www.gutenberg.org/cache/epub/100/pg100.txt' 
# Get Shakespeare text 
response = requests.get(shakespeare_url) 
shakespeare_file = response.content 
# Decode binary into string 
shakespeare_text = shakespeare_file.decode('utf-8') 
# Drop first few descriptive paragraphs. 
shakespeare_text = shakespeare_text[7675:] 
print(len(shakespeare_text)) # Number of characters 

5582212


**English-German sentence translation data:** The Tatoeba project (http://tatoeba.org) collects sentence translations in many languages. Their data has been released under the Creative Commons License. From this data, ManyThings.org (http://www.manythings.org) has compiled sentence-to-sentence translations in text files that are available for download. Here, we will use the English-German translation file, but you can change the URL to whichever languages you would like to use:



In [54]:
import requests 
import io 
from zipfile import ZipFile 
sentence_url = 'http://www.manythings.org/anki/deu-eng.zip' 
r = requests.get(sentence_url) 
z = ZipFile(io.BytesIO(r.content)) 
file = z.read('deu.txt') 
# Format Data 
eng_ger_data = file.decode() 
eng_ger_data = eng_ger_data.encode('ascii',errors='ignore') 
eng_ger_data = eng_ger_data.decode().split('\n') 
eng_ger_data = [x.split('\t') for x in eng_ger_data if len(x)>=1] 
[english_sentence, german_sentence] = [list(x) for x in zip(*eng_ger_data)] 
print(len(english_sentence)) 
print(len(german_sentence)) 
print(eng_ger_data[10]) 

176692
176692
['Go on.', 'Mach weiter.']
