# 1 - Getting Started with TensorFlow

In [1]:
import tensorflow as tf
import numpy as np

/Library/Anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.6 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.7
  return f(*args, **kwds)


## Declaring Tensors

### 1.1 Fixed tensors:



In [2]:
row_dim = 4
col_dim = 5
sess = tf.Session()

In [3]:
#Create a zero filled tensor. Use the following:
zero_tsr = tf.zeros([row_dim, col_dim])
print(zero_tsr)
sess.run(zero_tsr)

Tensor("zeros:0", shape=(4, 5), dtype=float32)


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)

In [4]:
# Create a one filled tensor. Use the following: 
ones_tsr = tf.ones([row_dim, col_dim])
print(ones_tsr)
sess.run(ones_tsr)

Tensor("ones:0", shape=(4, 5), dtype=float32)


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)

In [5]:
#Create a constant filled tensor. Use the following: 
filled_tsr = tf.fill([row_dim, col_dim], 42)
print(filled_tsr)
sess.run(filled_tsr)

Tensor("Fill:0", shape=(4, 5), dtype=int32)


array([[42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42]], dtype=int32)

In [6]:
#Create a tensor out of an existing constant. Use the following:
constant_tsr = tf.constant([1,2,3])
print(constant_tsr)
sess.run(constant_tsr)

Tensor("Const:0", shape=(3,), dtype=int32)


array([1, 2, 3], dtype=int32)

### 1.2 Tensors of similar shape

In [7]:
#We can also initialize variables based on the shape of other tensors, as follows:
zeros_similar = tf.zeros_like(constant_tsr)
ones_similar = tf.ones_like(constant_tsr)
print(zeros_similar,'\n', ones_similar)
print('zeros_similar: ', sess.run(zeros_similar))
print('ones_similar: ', sess.run(ones_similar))



Tensor("zeros_like:0", shape=(3,), dtype=int32) 
 Tensor("ones_like:0", shape=(3,), dtype=int32)
zeros_similar:  [0 0 0]
ones_similar:  [1 1 1]


### 1.3 Sequence tensors:

In [8]:
# TensorFlow allows us to specify tensors that contain defined intervals. The following functions behave very 
# similarly to the range() outputs and numpy's linspace() outputs. See the following function:
linear_tsr = tf.linspace(start=0.0, stop=1, num=3)
print(linear_tsr)
sess.run(linear_tsr)

Tensor("LinSpace:0", shape=(3,), dtype=float32)


array([0. , 0.5, 1. ], dtype=float32)

In [9]:
# The resulting tensor is the sequence [0.0, 0.5, 1.0]. 
# Note that this function includes the specified stop value. See the following function:
# The result is the sequence [6, 9, 12]. Note that this function does not include the limit value.
integer_seq_tsr = tf.range(start=6, limit=15, delta=3)
print(integer_seq_tsr)
sess.run(integer_seq_tsr)

Tensor("range:0", shape=(3,), dtype=int32)


array([ 6,  9, 12], dtype=int32)

### 1.4 Random tensors:

In [10]:
# Note that this random uniform distribution draws from the interval 
# that includes the minval but not the maxval (minval <= x < maxval).
randunif_tsr = tf.random_uniform([row_dim, col_dim], minval=0, maxval=1)
print(randunif_tsr)
sess.run(randunif_tsr)

Tensor("random_uniform:0", shape=(4, 5), dtype=float32)


array([[0.82605803, 0.14643288, 0.61644924, 0.81825733, 0.13137698],
       [0.9981047 , 0.06304049, 0.17409086, 0.89099455, 0.16054821],
       [0.38351953, 0.60555375, 0.8205613 , 0.36453366, 0.12410045],
       [0.06437266, 0.26157522, 0.10893536, 0.4633211 , 0.8711101 ]],
      dtype=float32)

In [11]:
# To get a tensor with random draws from a normal distribution, as follows:
randnorm_tsr = tf.random_normal([row_dim, col_dim], mean=0.0, stddev=1.0)
print(randnorm_tsr)
sess.run(randnorm_tsr)

Tensor("random_normal:0", shape=(4, 5), dtype=float32)


array([[ 1.2726241 , -2.1672246 , -1.2462734 ,  0.05829038, -1.0773718 ],
       [ 0.14019506, -0.08897112,  0.9030555 , -1.3995047 , -1.2107377 ],
       [ 1.4157252 ,  0.5049212 , -0.5218605 ,  0.62831753,  1.377711  ],
       [ 0.8937944 ,  0.13170552, -1.7020888 , -0.5182833 ,  0.1857618 ]],
      dtype=float32)

In [12]:
# There are also times when we wish to generate normal random values that are assured within certain bounds.
# The truncated_normal() function always picks normal values within two standard deviations of the specified mean.
# See the following:
runcnorm_tsr = tf.truncated_normal([row_dim, col_dim], mean=0.0, stddev=1.0)
print(runcnorm_tsr)
sess.run(runcnorm_tsr)

Tensor("truncated_normal:0", shape=(4, 5), dtype=float32)


array([[-0.8728942 ,  0.6087043 ,  0.6540223 , -0.26477733, -0.4997692 ],
       [-0.96437234,  0.32361802,  1.2269399 ,  1.8541167 ,  1.5350804 ],
       [-1.6191068 ,  1.9237299 , -0.64776963, -0.11210471,  1.5593188 ],
       [-1.4118893 ,  0.41072288,  0.07293078,  0.31745413,  0.595975  ]],
      dtype=float32)

- We might also be interested in randomizing entries of arrays. To accomplish this, there are two functions that help us: ```random_shuffle()``` and ``random_crop()``. See the following:

In [13]:
# shuffled_output = tf.random_shuffle(runcnorm_tsr)
# cropped_output = tf.random_crop(runcnorm_tsr, 2)

# print('shuffled_output: ', shuffled_output, sess.run(shuffled_output))
# print('cropped_output: ', cropped_output,sess.run(cropped_output))


In [14]:
# Later on in this book, we will be interested in randomly cropping an image of size (height, width, 3) where there are three color spectrums. To fix a dimension in the cropped_output, you must give it the maximum size in that dimension:
#cropped_image = tf.random_crop(my_image, [height/2, width/2, 3])

## Using Placeholders and Variables


Placeholders and variables are key tools for using computational graphs in TensorFlow. We must understand the difference and when to best use them to our advantage.
### Getting ready
One of the most important distinctions to make with the data is whether it is a placeholder or a variable. Variables are the parameters of the algorithm and TensorFlow keeps track of how to change these to optimize the algorithm. Placeholders are objects that allow you to feed in data of a specific type and shape and depend on the results of the computational graph, such as the expected outcome of a computation.

In [15]:
my_var = tf.Variable(tf.zeros([2,3]))
sess = tf.Session()
initialize_op = tf.global_variables_initializer ()
sess.run(initialize_op)
sess.run(my_var)

array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [16]:
sess = tf.Session()
x = tf.placeholder(tf.float32, shape=[2,2])
y = tf.identity(x)
x_vals = np.random.rand(2,2)
sess.run(y, feed_dict={x: x_vals})
# Note that sess.run(x, feed_dict={x: x_vals}) will result in a self-referencing error.

array([[0.19870183, 0.54482615],
       [0.1335896 , 0.9235258 ]], dtype=float32)

During the run of the computational graph, we have to tell TensorFlow when to initialize the variables we have created. TensorFlow must be informed about when it can initialize the variables. While each variable has an initializer method, the most common way to do this is to use the helper function, which is `global_variables_initializer()`.
This function creates an operation in the graph that initializes all the variables we have created, as follows:



In [17]:
initializer_op = tf.global_variables_initializer()
sess.run(initializer_op)

But if we want to initialize a variable based on the results of initializing another variable, we have to initialize variables in the order we want, as follows:

In [18]:
sess = tf.Session()
first_var = tf.Variable(tf.zeros([2,3]))
sess.run(first_var.initializer)
second_var = tf.Variable(tf.zeros_like(first_var))
# Depends on first_var
sess.run(second_var.initializer)

## Working with Matrices

In [19]:
sess = tf.Session()

1. Creating matrices: We can create two-dimensional matrices from numpy arrays or nested lists, as we described in the earlier section on tensors. We can also use the tensor creation functions and specify a two-dimensional shape for functions such as `zeros()`, `ones()`, `truncated_normal()`, and so on. TensorFlow also allows us to create a diagonal matrix from a one-dimensional array or list with the function `diag()`, as follows:

In [20]:
identity_matrix = tf.diag([1.0, 1.0, 1.0])
A = tf.truncated_normal([2,3])
B = tf.fill([2,3], 5.0)
C = tf.random_uniform([3,2])
D = tf.convert_to_tensor(np.array([[1., 2., 3.],[-3., -7., -1.],[0., 5., -2.]]))
print('identity_matrix: \n', sess.run(identity_matrix))
print('A: \n', sess.run(A))
print('B: \n', sess.run(B))
print('C: \n', sess.run(C))
print('D: \n', sess.run(D))

identity_matrix: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
A: 
 [[ 0.29070416 -0.8347452   0.81752175]
 [-1.4419012   0.3473675   1.2008007 ]]
B: 
 [[5. 5. 5.]
 [5. 5. 5.]]
C: 
 [[0.89956474 0.68351626]
 [0.57887316 0.91580856]
 [0.11133242 0.90355957]]
D: 
 [[ 1.  2.  3.]
 [-3. -7. -1.]
 [ 0.  5. -2.]]


In [21]:
# Addition and subtraction uses the following function: 
print(sess.run(A+B))

[[5.2825418 4.4700584 4.909249 ]
 [5.713708  6.374424  6.711489 ]]


In [22]:
print(sess.run(B-B))

[[0. 0. 0.]
 [0. 0. 0.]]


In [23]:
# Also, the function matmul() has arguments that specify whether or not to transpose
# the arguments before multiplication or whether each matrix is sparse.

print(sess.run(tf.matmul(B, identity_matrix)))

[[5. 5. 5.]
 [5. 5. 5.]]


In [25]:
# Transpose the arguments as follows:
print(sess.run(tf.transpose(C)))

[[0.6570883  0.1834464  0.69341624]
 [0.4779626  0.6442077  0.8964844 ]]


In [26]:
# For the determinant, use the following:
print(sess.run(tf.matrix_determinant(D)))

-37.99999999999999


In [27]:
# Inverse
print(sess.run(tf.matrix_inverse(D)))

[[-0.5        -0.5        -0.5       ]
 [ 0.15789474  0.05263158  0.21052632]
 [ 0.39473684  0.13157895  0.02631579]]


In [28]:
# For the Cholesky decomposition, use the following:
print(sess.run(tf.cholesky(identity_matrix)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# For Eigenvalues and eigenvectors, use the following code:
print(sess.run(tf.self_adjoint_eig(D))